### ISSUE TITLE
RCO Flags???

### ISSUE THREAD

**Issue by ghost** [WilliamAnimate/optimize-my-roblos#1]
What I've seen in the flag file are just RCO flags, they are very unstable, and you yourself don't even know what they even do, maybe just make a GUI version of this and maybe update it over time???: https://rentry.co/robloxpotatofflags

**Comment by a-catgirl-dev** [comment]
Thanks for letting me know, i'll make changes in a moment.

**Comment by a-catgirl-dev** [comment]
completed in [v1.1.0](https://github.com/WilliamAnimate/optimize-my-roblos/releases/tag/v1.1.0)
