### ISSUE TITLE
Studio support

### ISSUE THREAD

**Issue by ghost** [WilliamAnimate/optimize-my-roblos#3]
It would be useful & not too hard to implement

To add onto this, it could also enable generally useful FFlags like light attenuation and extended light range

**Comment by a-catgirl-dev** [comment]
will work on this tonight, any special FFlags I should add/remove for the Studio version?

**Comment by ghost** [comment]
> will work on this tonight, any special FFlags I should add/remove for the Studio version?

just the ones i mentioned
```json
"FFlagNewLightAttenuation": true,
"FFlagExtendedLightRanges2": true,
```
attenuation is apparently buggy so that could probably be off by default
DFIntTaskSchedulerTargetFps could also be unlimited to 999 for both studio & client since there's no point in capping it to 120 when you might aswell squeeze as much performance as you can out of your hardware (or for higher refresh rate monitors)

**Comment by a-catgirl-dev** [comment]
completed in [v1.2.0](https://github.com/WilliamAnimate/optimize-my-roblos/releases/tag/v1.2.0)
